name: Discord Comment Notif

on:
  release: 
    types: published
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom Discord message
        uses: chase-roohms/discord-notify@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "## New Version Released On ${{ github.repository }}: ${{ github.event.release.name }}!\nChangelog: ${{ github.event.release.html_url }}"
